name: CICD
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x,1.16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golinto version
          go get -u github.com/stretchr/testify/assert

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run vet & lint
        uses: make check

      - name: Run testing
        run: make test

      - name: Run coverage
        run: make coverage

      - name: Upload coverage
        uses: actions/checkout@master
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

